### ISSUE TITLE
[Error: connect ETIMEDOUT]

### ISSUE THREAD

**Issue by zzmarzomber** [brouznouf/fivem-mysql-async#123] opened 2020-05-06 10:03 UTC
Hello, I have this error in my vps, but in my local pc, it does not come out, I get an error
![unknown](https://user-images.githubusercontent.com/64898096/81165028-ac19d900-8f67-11ea-88de-84a067fa43e9.png)

**Comment by zoomlordir** [comment] 2020-05-11 18:23
The reason for this error is the version of resources
resources need **sync** by **SQL** must have a version and this version must be same in **mysql-async** and resource
**so you need to use older version of mysql-async like version 2.0.0 or update your resources**

**Comment by GHMatti** [comment] 2020-05-12 12:45
Which server are you running?

**Comment by benitoll** [comment] 2020-05-14 03:01
> The reason for this error is the version of resources
> resources need **sync** by **SQL** must have a version and this version must be same in **mysql-async** and resource
> **so you need to use older version of mysql-async like version 2.0.0 or update your resources**

Can you further explain or post an example?

**Comment by GHMatti** [comment] 2020-05-16 21:13
Would anyone who is reliably getting the timeout error try this branch and report back?

https://github.com/brouznouf/fivem-mysql-async/tree/patch-etimeoutd

**Comment by zoomlordir** [comment] 2020-05-16 21:25
> > The reason for this error is the version of resources
> > resources need **sync** by **SQL** must have a version and this version must be same in **mysql-async** and resource
> > **so you need to use older version of mysql-async like version 2.0.0 or update your resources**
> 
> Can you further explain or post an example?

ommm you use a old resource and resource use old mysql functions and in new mysql  functions are different so resource cant connect to mysql with old  functions 
you know i cant explain more then that
you can ask the developer of the resource for version of mysql

**Comment by zoomlordir** [comment] 2020-05-16 21:28
> Would anyone who is reliably getting the timeout error try this branch and report back?
> 
> https://github.com/brouznouf/fivem-mysql-async/tree/patch-etimeoutd

that's really weird error and i had this error before in my VPS and this error never happened on my local server .. same files same sql

**Comment by GHMatti** [comment] 2020-05-17 06:00
I know why it happens, the issue is to repro it properly. Should be fixable for newer version.

I am just not sure if the branch helps.

**Comment by GHMatti** [comment] 2020-05-18 12:49
Issue should be fixed with #127

**Closed by GHMatti** 2020-05-18 12:49 UTC

**Comment by beauflexx** [comment] 2021-03-26 18:27
how do i download #127 hahaha im new to github
but this issue has been driving me insane trying to sort
