### ISSUE TITLE
Error On startup Linux

### ISSUE THREAD

**Issue by Cactusje** [brouznouf/fivem-mysql-async#76] opened 2019-05-09 16:24 UTC
Hello, 

I am running my FiveM server on a Linux VPS with Ubuntu 18.04. On startup I get a whole line of errors, which has to do with mysql-async. Here are they:

```Error: (node:7888) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT
    at PoolConnection.Connection._handleConnectTimeout (mysql-async.js:1004:13)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:422:8)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
    --------------------
    at Protocol._enqueue (mysql-async.js:6167:48)
    at Protocol.handshake (mysql-async.js:6074:23)
    at PoolConnection.connect (mysql-async.js:711:18)
    at Pool.getConnection (mysql-async.js:4753:16)
    at Pool.query (mysql-async.js:4907:8)
    at Promise (mysql-async.js:5146:12)
    at new Promise (<anonymous>)
    at execute (mysql-async.js:5143:26)
    at Object.global.exports [as callback] (mysql-async.js:5161:5)
    at citizen:/scripting/v8/main.js:96:41
Error: (node:7888) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
Error: (node:7888) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: (node:7888) UnhandledPromiseRejectionWarning: Error: Handshake inactivity timeout
    at Handshake.<anonymous> (mysql-async.js:6183:17)
    at emitNone (events.js:106:13)
    at Handshake.emit (events.js:208:7)
    at Handshake._onTimeout (mysql-async.js:316:8)
    at Timer._onTimeout (mysql-async.js:13221:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
    --------------------
    at Protocol._enqueue (mysql-async.js:6167:48)
    at Protocol.handshake (mysql-async.js:6074:23)
    at PoolConnection.connect (mysql-async.js:711:18)
    at Pool.getConnection (mysql-async.js:4753:16)
    at Pool.query (mysql-async.js:4907:8)
    at Promise (mysql-async.js:5146:12)
    at new Promise (<anonymous>)
    at execute (mysql-async.js:5143:26)
    at Object.global.exports [as callback] (mysql-async.js:5169:5)
    at citizen:/scripting/v8/main.js:96:41
Error: (node:7888) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
Error: (node:7888) UnhandledPromiseRejectionWarning: Error: Handshake inactivity timeout
    at Handshake.<anonymous> (mysql-async.js:6183:17)
    at emitNone (events.js:106:13)
    at Handshake.emit (events.js:208:7)
    at Handshake._onTimeout (mysql-async.js:316:8)
    at Timer._onTimeout (mysql-async.js:13221:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
    --------------------
    at Protocol._enqueue (mysql-async.js:6167:48)
    at Protocol.handshake (mysql-async.js:6074:23)
    at PoolConnection.connect (mysql-async.js:711:18)
    at Pool.getConnection (mysql-async.js:4753:16)
    at Pool.query (mysql-async.js:4907:8)
    at Promise (mysql-async.js:5146:12)
    at new Promise (<anonymous>)
    at execute (mysql-async.js:5143:26)
    at Object.global.exports [as callback] (mysql-async.js:5169:5)
    at citizen:/scripting/v8/main.js:96:41
Error: (node:7888) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
Error: (node:7888) UnhandledPromiseRejectionWarning: Error: Handshake inactivity timeout
    at Handshake.<anonymous> (mysql-async.js:6183:17)
    at emitNone (events.js:106:13)
    at Handshake.emit (events.js:208:7)
    at Handshake._onTimeout (mysql-async.js:316:8)
    at Timer._onTimeout (mysql-async.js:13221:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
    --------------------
    at Protocol._enqueue (mysql-async.js:6167:48)
    at Protocol.handshake (mysql-async.js:6074:23)
    at PoolConnection.connect (mysql-async.js:711:18)
    at Pool.getConnection (mysql-async.js:4753:16)
    at Pool.query (mysql-async.js:4907:8)
    at Promise (mysql-async.js:5146:12)
    at new Promise (<anonymous>)
    at execute (mysql-async.js:5143:26)
    at Object.global.exports [as callback] (mysql-async.js:5169:5)
    at citizen:/scripting/v8/main.js:96:41
Error: (node:7888) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
Error: (node:7888) UnhandledPromiseRejectionWarning: Error: Handshake inactivity timeout
    at Handshake.<anonymous> (mysql-async.js:6183:17)
    at emitNone (events.js:106:13)
    at Handshake.emit (events.js:208:7)
    at Handshake._onTimeout (mysql-async.js:316:8)
    at Timer._onTimeout (mysql-async.js:13221:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
    --------------------
    at Protocol._enqueue (mysql-async.js:6167:48)
    at Protocol.handshake (mysql-async.js:6074:23)
    at PoolConnection.connect (mysql-async.js:711:18)
    at Pool.getConnection (mysql-async.js:4753:16)
    at Pool.query (mysql-async.js:4907:8)
    at Promise (mysql-async.js:5146:12)
    at new Promise (<anonymous>)
    at execute (mysql-async.js:5143:26)
    at Object.global.exports [as callback] (mysql-async.js:5169:5)
    at citizen:/scripting/v8/main.js:96:41
Error: (node:7888) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
Error: (node:7888) UnhandledPromiseRejectionWarning: Error: Handshake inactivity timeout
    at Handshake.<anonymous> (mysql-async.js:6183:17)
    at emitNone (events.js:106:13)
    at Handshake.emit (events.js:208:7)
    at Handshake._onTimeout (mysql-async.js:316:8)
    at Timer._onTimeout (mysql-async.js:13221:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
    --------------------
    at Protocol._enqueue (mysql-async.js:6167:48)
    at Protocol.handshake (mysql-async.js:6074:23)
    at PoolConnection.connect (mysql-async.js:711:18)
    at Pool.getConnection (mysql-async.js:4753:16)
    at Pool.query (mysql-async.js:4907:8)
    at Promise (mysql-async.js:5146:12)
    at new Promise (<anonymous>)
    at execute (mysql-async.js:5143:26)
    at Object.global.exports [as callback] (mysql-async.js:5161:5)
    at citizen:/scripting/v8/main.js:96:41
Error: (node:7888) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
Error: (node:7888) UnhandledPromiseRejectionWarning: Error: Handshake inactivity timeout
    at Handshake.<anonymous> (mysql-async.js:6183:17)
    at emitNone (events.js:106:13)
    at Handshake.emit (events.js:208:7)
    at Handshake._onTimeout (mysql-async.js:316:8)
    at Timer._onTimeout (mysql-async.js:13221:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
    --------------------
    at Protocol._enqueue (mysql-async.js:6167:48)
    at Protocol.handshake (mysql-async.js:6074:23)
    at PoolConnection.connect (mysql-async.js:711:18)
    at Pool.getConnection (mysql-async.js:4753:16)
    at Pool.query (mysql-async.js:4907:8)
    at Promise (mysql-async.js:5146:12)
    at new Promise (<anonymous>)
    at execute (mysql-async.js:5143:26)
    at Object.global.exports [as callback] (mysql-async.js:5169:5)
    at citizen:/scripting/v8/main.js:96:41
Error: (node:7888) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
Error: (node:7888) UnhandledPromiseRejectionWarning: Error: Handshake inactivity timeout
    at Handshake.<anonymous> (mysql-async.js:6183:17)
    at emitNone (events.js:106:13)
    at Handshake.emit (events.js:208:7)
    at Handshake._onTimeout (mysql-async.js:316:8)
    at Timer._onTimeout (mysql-async.js:13221:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
    --------------------
    at Protocol._enqueue (mysql-async.js:6167:48)
    at Protocol.handshake (mysql-async.js:6074:23)
    at PoolConnection.connect (mysql-async.js:711:18)
    at Pool.getConnection (mysql-async.js:4753:16)
    at Pool.query (mysql-async.js:4907:8)
    at Promise (mysql-async.js:5146:12)
    at new Promise (<anonymous>)
    at execute (mysql-async.js:5143:26)
    at Object.global.exports [as callback] (mysql-async.js:5169:5)
    at citizen:/scripting/v8/main.js:96:41
Error: (node:7888) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
Error: (node:7888) UnhandledPromiseRejectionWarning: Error: Handshake inactivity timeout
    at Handshake.<anonymous> (mysql-async.js:6183:17)
    at emitNone (events.js:106:13)
    at Handshake.emit (events.js:208:7)
    at Handshake._onTimeout (mysql-async.js:316:8)
    at Timer._onTimeout (mysql-async.js:13221:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
    --------------------
    at Protocol._enqueue (mysql-async.js:6167:48)
    at Protocol.handshake (mysql-async.js:6074:23)
    at PoolConnection.connect (mysql-async.js:711:18)
    at Pool.getConnection (mysql-async.js:4753:16)
    at Pool.query (mysql-async.js:4907:8)
    at Promise (mysql-async.js:5146:12)
    at new Promise (<anonymous>)
    at execute (mysql-async.js:5143:26)
    at Object.global.exports [as callback] (mysql-async.js:5169:5)
    at citizen:/scripting/v8/main.js:96:41
Error: (node:7888) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
Error: (node:7888) UnhandledPromiseRejectionWarning: Error: Handshake inactivity timeout
    at Handshake.<anonymous> (mysql-async.js:6183:17)
    at emitNone (events.js:106:13)
    at Handshake.emit (events.js:208:7)
    at Handshake._onTimeout (mysql-async.js:316:8)
    at Timer._onTimeout (mysql-async.js:13221:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
    --------------------
    at Protocol._enqueue (mysql-async.js:6167:48)
    at Protocol.handshake (mysql-async.js:6074:23)
    at PoolConnection.connect (mysql-async.js:711:18)
    at Pool.getConnection (mysql-async.js:4753:16)
    at Pool.query (mysql-async.js:4907:8)
    at Promise (mysql-async.js:5146:12)
    at new Promise (<anonymous>)
    at execute (mysql-async.js:5143:26)
    at Object.global.exports [as callback] (mysql-async.js:5169:5)
    at citizen:/scripting/v8/main.js:96:41
Error: (node:7888) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)```

Hopefully anyone can help me with this.

Thanks,
Jorrit

**Comment by GHMatti** [comment] 2019-05-09 16:34
Would you mind posting the first error that happens and not just the trace?

**Comment by Cactusje** [comment] 2019-05-09 16:54
I think that the whole error will help better tracking the issue

**Comment by Cactusje** [comment] 2019-05-09 17:31
Duplicate?

**Comment by GHMatti** [comment] 2019-05-09 17:56
Duplicate of #64

**Comment by Cactusje** [comment] 2019-05-09 18:47
But this this gonna get resolved?

**Comment by GHMatti** [comment] 2019-05-09 20:21
Unlikely in #64, you will need to provide maybe a full log.

`./run.sh +exec server.cfg > output.log` to create a log.

**Comment by Cactusje** [comment] 2019-05-09 20:27
[output.log](https://github.com/brouznouf/fivem-mysql-async/files/3163875/output.log)
It looks like the error has changed, still weird error though since my string is totally fine

**Comment by GHMatti** [comment] 2019-05-09 20:33
Error: (node:10331) UnhandledPromiseRejectionWarning: Error: Empty mysql_connection_string detected.

How about you properly use set `mysql_connection_string` To connect to mysql?

**Comment by Cactusje** [comment] 2019-05-09 20:35
As I said I have property set it, for some reason the issue changed. I'll send you the string

**Comment by Cactusje** [comment] 2019-05-09 20:36
set mysql_connection_string "server=5.226.143.66;uid=fivem;password=CENSORED;database=essentialmode"

**Comment by GHMatti** [comment] 2019-05-09 20:37
try and set it before you call the resources. Somehow it says it is empty.

**Comment by Cactusje** [comment] 2019-05-09 20:37
It's the first line of the server.cfg

**Comment by GHMatti** [comment] 2019-05-09 20:38
try and delete the cache folder.

**Comment by Cactusje** [comment] 2019-05-09 20:39
Alright one second

**Comment by Cactusje** [comment] 2019-05-09 20:40
No startup errors, let me login to the server

**Comment by Cactusje** [comment] 2019-05-09 20:43
Suddently it wasn't done yet.
[output.log](https://github.com/brouznouf/fivem-mysql-async/files/3163933/output.log)

Also got 2 errors ingame

**Comment by Cactusje** [comment] 2019-05-09 20:45
Is it possible that my server.cfg is corrupt or anything? Also the option es_enablecustomdata from essentialmode does nothing

**Comment by GHMatti** [comment] 2019-05-09 20:45
`[91mError: (node:10481) UnhandledPromiseRejectionWarning: Error: Empty mysql_connection_string detected.`

still the empty connection string, but there are a few more errors.

**Comment by GHMatti** [comment] 2019-05-09 20:45
Maybe get support on the forums for it.

**Comment by Cactusje** [comment] 2019-05-09 20:47
I will this errors f***** up my whole playerbase. First night we had 32 players online. Next day the server went down and it haven't been up for several days. I will create a topic

**Comment by LySoon** [comment] 2019-05-10 13:57
i have the same issue too 
im using linux and updated to latest version..

**Comment by LySoon** [comment] 2019-05-10 14:05
at Protocol._parsePacket (mysql-async.js:6326:23)
    at Parser._parsePacket (mysql-async.js:6937:10)
    at Parser.write (mysql-async.js:6547:10)
    at Protocol.write (mysql-async.js:6073:16)
    at Socket.<anonymous> (mysql-async.js:683:28)
    at Socket.<anonymous> (mysql-async.js:1117:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    --------------------
    at Protocol._enqueue (mysql-async.js:6179:48)
    at Protocol.handshake (mysql-async.js:6086:23)
    at PoolConnection.connect (mysql-async.js:711:18)
    at Pool.getConnection (mysql-async.js:4753:16)
    at Pool.releaseConnection (mysql-async.js:4862:10)
    at Pool._removeConnection (mysql-async.js:4982:8)
    at Pool._purgeConnection (mysql-async.js:4963:8)
    at Handshake.onConnect (mysql-async.js:4762:14)
    at Handshake.<anonymous> (mysql-async.js:1117:10)
    at Handshake._callback (mysql-async.js:1083:16)
Error: (node:28263) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 19)

**Comment by Cactusje** [comment] 2019-05-10 16:36
@LySoon I fixed all mine. Contact me on discord Jorrit#0001 it has nothing todo with MySQL async

**Comment by LySoon** [comment] 2019-05-11 01:17
Request Sent ❤️

**Closed** 2019-05-11 15:31 UTC
Labels: awaiting repro, duplicate
