### ISSUE TITLE
Transactions broken (DONT USE WILL CRASH MYSQL CONNECTION)

### ISSUE THREAD

**Issue by benzon** [brouznouf/fivem-mysql-async#129] opened 2020-05-22 16:23 UTC
Hi,

Tryed out the MySQL Transaction with latest version, and it's not fixed it's utterly broken.

Testet with following code.

```
SaveStorageMySQL = function()
    -- Create sqls table
	local sqls = {}
	
	-- Add each player save query and params to the two tables
	for k, v in ipairs(save) do
		local query = 'UPDATE drp_storage SET type = @type, sid = @sid, data = @data WHERE type = @type and sid = @sid'
		local parameters = {
			['@type'] = v.type,
			['@sid'] = v.sid,
			['@data'] = json.encode(storage[v.type][v.sid])
		}
		table.insert(sqls, {
			query = query,
			parameters = parameters
		})
	end

	-- Execute the transaction
	MySQL.Async.transaction(sqls, cb)
end
```

The Save works, but if the resource is restartet a couple of times it locks up fully, and even normal MySQL connections from the fxserver wont work unless fx is restartet.

**Comment by benzon** [comment] 2020-05-22 16:42
Not sure why transaction ends up locking up MySQL 100% but ye there is a issue with this.

**Comment by GHMatti** [comment] 2020-05-22 21:06
Cannot reproduce that locally. Doing multiple transactions works fine for me.

Can you create a minimum working example, so i have the chance of reproducing your issue?

**Comment by benzon** [comment] 2020-05-22 23:47
Did you remember to try and restart the resource a couple of times ? 5-10 times and suddenly it locks up.

**Comment by benzon** [comment] 2020-05-23 01:21
Only test code i got is a script im working on, would not mind sharing it with you, but dont wanna share it with the world not right now adleest.

But tryed to use transactions for saving but if i restart it a couple of times it ends in a lock up.

**Comment by benzon** [comment] 2020-05-23 01:21
If i revert over to normal Async calls to save the date no lock up on several restarts of the resource.

**Comment by GHMatti** [comment] 2020-05-23 06:17
With the next version it will be fixed. You can run

`npm i && npm run build` with node.js installed in the source folder to get a development build.

**Closed** 2020-05-23 06:16 UTC

**Comment by benzon** [comment] 2020-05-23 14:39
Sounds good, so there was a flaw in the code ? nice that it got fixed.

**Comment by GHMatti** [comment] 2020-05-24 06:26
https://github.com/brouznouf/fivem-mysql-async/issues/129#issuecomment-632946065

That comment made it so i could reproduce the issue, meaning i could see myself what was wrong, from which on it was really easy to fix. 

If you have an issue, and tell me how i can trigger it myself, I can actually fix stuff; and that often really quickly if it is important broken stuff.

Sadly nobody does that when reporting an issue. I might have a hunch where stuff is wrong in some cases, but with limited time, I often do not have the time to look in detail.

e.g. the high tick rate people, it is likely their server is just overloaded with resources.
