### ISSUE TITLE
Emojis not showing

### ISSUE THREAD

**Issue by HumanTree92** [brouznouf/fivem-mysql-async#50] opened 2018-11-06 01:03 UTC
So i have 2 FiveM servers. 1 is a Test Server & the other is our Main Server. They have exactly the same scripts & code. Except our Main Server is using mysql-async V2.1.1 & our Test Server is using the Latest version of mysql-async. The problem that i am having is Emoji's are not showing up correctly in the latest version. So maybe you can help me figure out why this is. Here are some links to what i am talking about.

[FiveM Main Server using mysql-async V2.1.1](https://i.imgur.com/yBNE7or.png)
[FiveM Test Server using latest version of mysql-async](https://i.imgur.com/4LIBfJT.png)

Also all Emoji's are from: https://unicode.org/emoji/charts/full-emoji-list.html

**Comment by GHMatti** [comment] 2018-11-06 07:43
Duplicate of #48

**Closed by GHMatti** 2018-11-06 07:43 UTC
Labels: duplicate
