### ISSUE TITLE
FX Server, Impossible to execute any request

### ISSUE THREAD

**Issue by qlaffont** [brouznouf/fivem-mysql-async#17] opened 2017-07-23 08:36 UTC
Hi,
I have this error : 
`
Exception loading assembly I18N: System.IO.FileNotFoundException: Unable to find the specified file.
`

How I can solve this ?
Regards
Quentin

**Comment by joelwurtz** [comment] 2017-07-26 16:56
I do not use any I18N assembly, seems strange, sure it's coming from this library ?

**Comment by anarchyrising** [comment] 2017-07-26 18:44
I'm pretty sure that I18N is a Mono error caused by the FXServer.  FiveM noted that these types of errors were harmless and may happen.  I have this error too and MySql-Async works fine.

**Comment by joelwurtz** [comment] 2017-07-26 22:49
That"s what i have seen also, closing this then

**Closed by joelwurtz** 2017-07-26 22:49 UTC
